# launch_isaac_ros2.py
import os
import argparse
from isaacsim import SimulationApp

# 1. Start Simulation App
CONFIG = {"headless": False}
simulation_app = SimulationApp(CONFIG)

import carb
import omni
from isaacsim.core.api import SimulationContext
from isaacsim.core.utils import extensions, prims
import omni.graph.core as og

# 2. Enable ROS2 Bridge
extensions.enable_extension("isaacsim.ros2.bridge")

# 3. Load USD Stage
# Default to the jetracer track generated by the project
usd_path = "/home/arika/Documents/arcpro/arcpro_system/src/examples/ARCPro_RL/arc_rl_isacc_sim/isacc_sim_usd/World0.usd"
if not os.path.exists(usd_path):
    print(f"Warning: {usd_path} not found. Loading default empty world.")
    omni.usd.get_context().new_stage()
else:
    omni.usd.get_context().open_stage(usd_path)

simulation_app.update()

# 4. Setup Action Graph for ROS2 -> Robot control
def setup_robot_bridge(robot_path="/mushr_tx2/mushr_fixed/base_footprint"):
    graph_path = f"{robot_path}/ActionGraph"
    keys = og.Controller.Keys
    (graph, nodes, _, _) = og.Controller.edit(
        graph_path,
        {
            keys.CREATE_NODES: [
                ("OnPlaybackTick", "omni.graph.action.OnPlaybackTick"),
                ("Ros2Context", "isaacsim.ros2.bridge.ROS2Context"),
                ("Ros2SubscribeAckermann", "isaacsim.ros2.bridge.ROS2SubscribeAckermannDrive"),
                ("AckermannController", "isaacsim.robot.wheeled_robots.AckermannController"),
                ("SteeringController", "isaacsim.core.nodes.IsaacArticulationController"),
                ("ThrottleController", "isaacsim.core.nodes.IsaacArticulationController"),
                # Camera publishing
                ("createViewport", "isaacsim.core.nodes.IsaacCreateViewport"),
                ("getRenderProduct", "isaacsim.core.nodes.IsaacGetViewportRenderProduct"),
                ("setCamera", "isaacsim.core.nodes.IsaacSetCameraOnRenderProduct"),
                ("cameraHelperRgb", "isaacsim.ros2.bridge.ROS2CameraHelper"),
            ],
            keys.SET_VALUES: [
                ("Ros2SubscribeAckermann.inputs:topicName", "/ackermann_cmd"),
                ("SteeringController.inputs:robotPath", robot_path),
                ("ThrottleController.inputs:robotPath", robot_path),
                # Map joints for Mushr
                ("SteeringController.inputs:jointNames", ["front_left_wheel_steer", "front_right_wheel_steer"]),
                ("ThrottleController.inputs:jointNames", [
                    "front_left_wheel_throttle", "front_right_wheel_throttle",
                    "back_left_wheel_throttle", "back_right_wheel_throttle"
                ]),
                # Ackermann Constants (Mushr based on research)
                ("AckermannController.inputs:wheelBase", 0.19), # Standard Mushr wheelbase is 0.19m
                ("AckermannController.inputs:trackWidth", 0.18), # Standard Mushr track width is 0.18m
                ("AckermannController.inputs:frontWheelRadius", 0.03),
                ("AckermannController.inputs:backWheelRadius", 0.03),
                # Camera
                ("cameraHelperRgb.inputs:topicName", "/camera/image_raw"),
                ("cameraHelperRgb.inputs:type", "rgb"),
                ("createViewport.inputs:viewportId", 0),
            ],
            keys.CONNECT: [
                ("OnPlaybackTick.outputs:tick", "Ros2SubscribeAckermann.inputs:execIn"),
                ("OnPlaybackTick.outputs:tick", "SteeringController.inputs:execIn"),
                ("OnPlaybackTick.outputs:tick", "ThrottleController.inputs:execIn"),
                ("OnPlaybackTick.outputs:tick", "createViewport.inputs:execIn"),
                
                ("Ros2Context.outputs:context", "Ros2SubscribeAckermann.inputs:context"),
                ("Ros2SubscribeAckermann.outputs:execOut", "AckermannController.inputs:execIn"),
                ("Ros2SubscribeAckermann.outputs:speed", "AckermannController.inputs:speed"),
                ("Ros2SubscribeAckermann.outputs:steeringAngle", "AckermannController.inputs:steeringAngle"),
                
                ("AckermannController.outputs:wheelAngles", "SteeringController.inputs:positionCommand"),
                ("AckermannController.outputs:wheelRotationVelocity", "ThrottleController.inputs:velocityCommand"),
                
                # Camera Flow
                ("createViewport.outputs:execOut", "getRenderProduct.inputs:execIn"),
                ("createViewport.outputs:viewport", "getRenderProduct.inputs:viewport"),
                ("getRenderProduct.outputs:execOut", "setCamera.inputs:execIn"),
                ("getRenderProduct.outputs:renderProductPath", "setCamera.inputs:renderProductPath"),
                ("setCamera.outputs:execOut", "cameraHelperRgb.inputs:execIn"),
                ("getRenderProduct.outputs:renderProductPath", "cameraHelperRgb.inputs:renderProductPath"),
            ],
        },
    )

# 5. Simulation Loop
simulation_context = SimulationContext()
setup_robot_bridge()
simulation_context.play()

while simulation_app.is_running():
    simulation_app.update()

simulation_context.stop()
simulation_app.close()
